import type { LoanProduct, SupplyTrack, UserProfile } from "@housing/schema";

const src = (page: number, text: string) => ({ page, text });

/** 행복주택 신혼부부 트랙 예시: 소득(가구·맞벌이 분기) + 신혼부부 OR 그룹 + 무주택 */
export const newlywedTrack: SupplyTrack = {
  name: "신혼부부·한부모가족",
  households: 40,
  unit_types: [{ name: "36", exclusive_area_m2: 36.9, households: 40 }],
  rule_groups: [
    { id: "income", mode: "all_of", label: "소득 기준" },
    { id: "newlywed", mode: "any_of", label: "신혼부부 자격" },
    { id: "basic", mode: "all_of", label: "기본 요건" },
  ],
  rules: [
    {
      group_id: "income",
      category: "income",
      applies_to: { household_size: 3, income_type: "single" },
      operator: "lte",
      value: 7_200_000,
      unit: "KRW_monthly",
      source: src(17, "3인 가구 100% 이하"),
      confidence: 0.95,
      verified: true,
    },
    {
      group_id: "income",
      category: "income",
      applies_to: { household_size: 3, income_type: "dual" },
      operator: "lte",
      value: 8_640_000,
      unit: "KRW_monthly",
      source: src(17, "3인 가구 맞벌이 120% 이하"),
      confidence: 0.95,
      verified: true,
    },
    {
      group_id: "newlywed",
      applies_to: {},
      category: "marriage",
      operator: "lte",
      value: 7,
      unit: "years",
      source: src(12, "혼인기간 7년 이내"),
      confidence: 0.95,
      verified: true,
    },
    {
      group_id: "newlywed",
      applies_to: {},
      category: "children",
      operator: "lte",
      value: 6,
      unit: "child_age",
      source: src(12, "6세 이하 자녀를 둔 한부모"),
      confidence: 0.9,
      verified: true,
    },
    {
      group_id: "basic",
      applies_to: {},
      category: "housing",
      operator: "gte",
      value: 0,
      unit: "months",
      source: src(11, "무주택세대구성원"),
      confidence: 0.98,
      verified: true,
    },
    {
      group_id: "basic",
      applies_to: {},
      category: "asset",
      operator: "lte",
      value: 345_000_000,
      unit: "KRW",
      source: src(18, "총자산 3억 4,500만 원 이하"),
      confidence: 0.95,
      verified: true,
    },
    {
      group_id: "basic",
      applies_to: {},
      category: "car_value",
      operator: "lte",
      value: 37_080_000,
      unit: "KRW",
      source: src(18, "자동차 3,708만 원 이하"),
      confidence: 0.95,
      verified: true,
    },
  ],
  pricing: [
    {
      unit_type: "36",
      kind: "rental",
      deposit: 60_000_000,
      monthly_rent: 280_000,
      conversion: { rate: 0.06, max_deposit: 110_000_000 },
      source: src(9, "36형 보증금 6,000만 원 / 월 28만 원"),
    },
  ],
};

export const youthTrack: SupplyTrack = {
  name: "청년",
  unit_types: [{ name: "26", households: 20 }],
  rule_groups: [{ id: "basic", mode: "all_of", label: "기본 요건" }],
  rules: [
    {
      group_id: "basic",
      applies_to: {},
      category: "age",
      operator: "between",
      value: [19, 39],
      unit: "years",
      source: src(12, "만 19세 이상 39세 이하"),
      confidence: 0.98,
      verified: true,
    },
    {
      group_id: "basic",
      applies_to: {},
      category: "marriage",
      operator: "in",
      value: ["single"],
      unit: "status",
      source: src(12, "미혼"),
      confidence: 0.9,
      verified: true,
    },
  ],
  pricing: [
    { unit_type: "26", kind: "rental", deposit: 40_000_000, monthly_rent: 200_000, source: src(9, "26형") },
  ],
};

export const marriedDualProfile: UserProfile = {
  age: 33,
  marriage: "married",
  marriage_years: 3,
  household_size: 3,
  children_count: 1,
  children_ages: [2],
  income_type: "dual",
  monthly_income: 8_000_000,
  total_assets: 150_000_000,
  car_value: 20_000_000,
  monthly_debt_payment: 0,
  is_homeless: true,
  homeless_months: 60,
  cash_on_hand: 30_000_000,
};

export const buteomok: LoanProduct = {
  id: "hf-buteomok-newlywed",
  name: "신혼부부 전용 버팀목 전세자금대출",
  provider: "주택도시기금",
  kind: "rental_deposit",
  rule_groups: [{ id: "basic", mode: "all_of", label: "기본" }],
  eligibility: [
    {
      group_id: "basic",
      applies_to: {},
      category: "marriage",
      operator: "lte",
      value: 7,
      unit: "years",
      source: { page: 1, text: "혼인기간 7년 이내" },
      confidence: 1,
      verified: true,
    },
    {
      group_id: "basic",
      applies_to: {},
      category: "income",
      operator: "lte",
      value: 7_500_000,
      unit: "KRW_monthly",
      source: { page: 1, text: "부부합산 연소득 7,500만 원 이하 → 월 환산" },
      confidence: 1,
      verified: true,
    },
  ],
  max_amount: 300_000_000,
  ltv: 0.8,
  term_months: 24,
  interest_only: true,
  rate_table: [
    { max_income: 2_500_000, annual_rate: 0.015 },
    { max_income: 5_000_000, annual_rate: 0.02 },
    { annual_rate: 0.027 },
  ],
  as_of_date: "2026-09-01",
};
